### ISSUE TITLE
$feat: update video for 2000FEAT (xdai)

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/website#21]
Replace lorem ipsum video to a Feature video on the homepage.

**Comment by Opixelum** [comment]
#22

**Comment by Opixelum** [comment]
Here is my $address 0xa1E9F75e5450e59aD6997BbB38D0855A21138CF8

**Comment by Opixelum** [comment]
#22

**Comment by Opixelum** [comment]
#22

**Comment by aurelien-brabant** [comment]
@Opixelum can you indeed 'slugify' the name of the video file? (i.e remove spaces and replace them by hyphen, mostly)

**Comment by n1c01a5** [comment]
@Opixelum it was the old contract except if you use Etherscan to do the txs you cannot claim directly in this thread so I will close this issues.
