### ISSUE TITLE
$feat: remove any lorem ipsum for wording on the homepage 20XDAI (xdai)

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/website#41]
See "Gestion de Projet" section.

**Comment by n1c01a5** [comment]
$feat: remove any lorem ipsum for wording on the homepage 20XDAI (Xdai)

**Comment by Opixelum** [comment]
$feat #42

**Comment by n1c01a5** [comment]
@Opixelum the translation is obviously did by IA. Can you use natural human translation ?

**Comment by Opixelum** [comment]
Done. Tell me what do you think about the new translation (#43)

**Comment by Opixelum** [comment]
$feat #43
