### ISSUE TITLE
$feat: optimize web image 15XDAI (xdai)

### ISSUE THREAD

**Issue by opixelum** [feature-sh/website#55]
- [ ] Check all images to see if they are already optimize
- [ ] Resize images if needed
- [ ] Compress images with https://tinyjpg.com/
- [ ] Compile png, jpg, ... to webp with `cwebp`

Info: SVG are already considered as optimized images.

**Comment by n1c01a5** [comment]
$feat with https://github.com/feature-sh/website/commit/319fa521383d698eb1f5fa73eb3d0ec6cd818d92
