### ISSUE TITLE
Move the dashboard URL to the global env

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/website#60]
## Description

The link to the dashboard (i.e *Sign In* link) is hardcoded.

To be more more flexible, we have to put this constant to a global var like `DASHBOARD_URL` created in `env-sample`.

**Comment by saksham-rastogi** [comment]
@n1c01a5 - Can I take this issue up?
**Solution approach**
Would be replacing the Sign In link (https://v1.dashboard.feature.sh) with process.env.DASHBOARD_URL in Header.tsx file and add DASHBOARD_URL key in .env-sample file

**Comment by saksham-rastogi** [comment]
I have opened up a pull request that will fix the enhancement - https://github.com/feature-sh/website/pull/61

**Comment by BLOCKCHAINDEVWEB** [comment]
The issue was resolved with this PR#https://github.com/feature-sh/website/pull/67, I close this one.
