### ISSUE TITLE
Wording translation

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/website#64]
The new wording of the website must cover by the translation files (`json`).

**Comment by BLOCKCHAINDEVWEB** [comment]
@n1c01a5 
Translation makes it possible to have longer texts from one language to another.
Words are hidden in the tables and the responsive requires some small alterations.

**Comment by n1c01a5** [comment]
Yes let's do some something simple. Just find a short translation.

**Comment by n1c01a5** [comment]
> @n1c01a5 Translation makes it possible to have longer texts from one language to another. Words are hidden in the tables and the responsive requires some small alterations.
> 
> Can we reduce the text to correct the problem?

Yes let's do some something simple. Just find a short translation.

**Comment by BLOCKCHAINDEVWEB** [comment]
$pr https://github.com/feature-sh/website/pull/66

**Comment by BLOCKCHAINDEVWEB** [comment]
$pr https://github.com/feature-sh/website/pull/66

**Comment by BLOCKCHAINDEVWEB** [comment]
Refund has been done !

**Comment by BLOCKCHAINDEVWEB** [comment]
These are expressions of 2 words each 'Build faster' and 'Build Trustless'.
Replacing or deleting one of the two words will give a completely different meaning to the original idea and fill the space just as much.
Also I reviewed the size of the text on the 1024 format only and I did not make a condition of the us-EN/fr url to determine the css.
